### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by Joni-Samanen** [lthms/spatial-shell#2]
Sorry for such a basic question, I don't have any experience with ocaml. I have been looking for something like this for a while.

**Comment by lthms** [comment]
The question is not basic, the fact that it is not explained better is an issue. I should try to provide precompiled binaries, at the very least. OCaml does not provide the most straightforward experience for newcomers.

I will try to come up with something. Out of curiosity, does your distribution of choice provide packages for `opam` and `ocaml`?

**Comment by Joni-Samanen** [comment]
Yeah I tried to fiddle around with opam, dune but really got nowhere. :D 

I run Arch Linux and opam and ocaml are installable via AUR

**Comment by lthms** [comment]
For the record, here is basically how I setup my install.

```
opam switch create . 4.14.0
opam install dune data-encoding clap poll
dune build --release
sudo cp _build/default/bin/spatial/main.exe /usr/local/bin/spatial
sudo cp _build/default/bin/spatialmsg/main.exe /usr/local/bin/spatialmsg
```

I also want to add my waybar config to this repository. I will do it later today or tomorrow.

**Comment by Joni-Samanen** [comment]
Thanks, maybe I'll give this another go! :)

**Comment by lthms** [comment]
I think I will keep it open until I get a proper “Getting Started” page.

**Comment by Armael** [comment]
The build instructions do not seem to work: there is no opam file in the repository, so `make build-deps` will only create an opam switch containing ocaml 5 and no other packages.

**Comment by lthms** [comment]
Oh, _right_, that is why I kept them before :sweat_smile: they are back now! Sorry about that.
